# Generated by Django 4.2.7 on 2023-11-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_ingestor', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
              ALTER TABLE logs ADD COLUMN search_vector tsvector GENERATED ALWAYS AS (
                  setweight(to_tsvector('english', coalesce(message, '')), 'A')
              ) STORED;
              CREATE INDEX logs_search_gin ON public.logs USING gin (search_vector);
            ''',
            reverse_sql = '''
              ALTER TABLE logs DROP COLUMN search_vector;
              DROP IDNEX logs_search_gin;
            '''
        )
    ]

