# Generated by Django 4.2.7 on 2023-11-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_ingestor', '0002_search_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loglevel',
            name='level',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='logresource',
            name='resource',
            field=models.CharField(unique=True),
        ),
    ]
